# Generated by Django 4.0.5 on 2022-09-20 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
